name: Build code, run unit test, run SAST, SCA, DAST security scans for Javascript App
on:
  push:
   
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
        node-version: 16
        cache: npm
    - run: npm install

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
        args: >
          -Dsonar.organization=juiceshoporg
          -Dsonar.projectKey=juiceshoporg
